version: '3'

services:
  web:
    build: ./backend/api_server
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/api_server:/app  # Правильное указание volume для синхронизации кода
    ports:
      - "8000:8000"  # Внутренний порт для Django
    networks:
      - django_network
      - frontend_network

  react-app:
    build: ./frontend
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"  # Внутренний порт для React
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - frontend_network

  spring-app:
    build: ./backend/main  # Path to your Spring Boot application
    ports:
      - "8090:8090"  # Expose the Spring Boot app on port 8090
    networks:
      - backend_network  # Adding to the backend network for connectivity with other services
      - frontend_network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"  # Перенаправляем запросы на порт 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Копируем конфигурацию Nginx
    depends_on:
      - web
      - react-app
      - spring-app  # Make sure nginx waits for spring-app to start
    networks:
      - django_network
      - frontend_network

networks:
  django_network:
  frontend_network:
  backend_network: