spring:
  application:
    name: corpo
  datasource:
    url: jdbc:mysql://192.168.0.109:3306/ecoprosvet
    username: ecoprosvet
    password: ecoprosvet180924
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8090