spring:
  application:
    name: corpo
  datasource:
    url: jdbc:mysql://192.168.0.109:3306/ecoprosvet
    username: ecoprosvet
    password: ecoprosvet180924
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          yandex:
            client-id: a6e307164bbe4ffabe73cfeff3b7371a
            client-secret: 137c5f39b2014593802f623821511b4f
            redirect-uri: "{baseUrl}/login/oauth2/code/yandex"
            authorization-grant-type: authorization_code
            scope: login:email
            client-name: Yandex
            provider: yandex
          vk:
            client-id: 52327148
            client-secret: mvL1LqKtcczdqToVwHpq
            redirect-uri: "{baseUrl}/login/oauth2/code/vk"
            authorization-grant-type: authorization_code
            scope: email
            client-name: VK
            provider: vk
        provider:
          yandex:
            authorization-uri: https://oauth.yandex.ru/authorize
            token-uri: https://oauth.yandex.ru/token
            user-info-uri: https://login.yandex.ru/info
            user-name-attribute: id
          vk:
            authorization-uri: https://oauth.vk.com/authorize
            token-uri: https://oauth.vk.com/access_token
            user-info-uri: https://api.vk.com/method/users.get
            user-name-attribute: response[0].id

server:
  port: 8090