version: '3.8'
name: 'ecoprosvet'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_ecoprosvet
    environment:
      MYSQL_ROOT_PASSWORD: root111000111!
      MYSQL_DATABASE: ecoprosvet
      MYSQL_USER: ecoprosvet
      MYSQL_PASSWORD: ecoprosvet180924
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my_network

  adminer:
    image: adminer
    container_name: adminer_ecoprosvet
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    networks:
      - my_network

volumes:
  mysql_data:

networks:
  my_network:
    driver: bridge